Repository kodeklubben/codeclub-viewer, pull requests merged in 2018-08, with the labels that each got.

#540 Issue 531 check if tags exists
  src/components/LessonPage/PrintInfo.js
  src/components/LessonPage/PrintInfo.scss
  src/pages/LessonPage.js
  src/pages/LessonPage.scss
Labels: PR: Needs Review

#534 Issue 394 and 518, clean up util.js
  src/components/CoursePage/LessonItem.js
  src/components/Flag.js
  src/components/LessonPage/ButtonRow.js
  src/components/LessonPage/Content.js
  src/components/LessonPage/ImprovePage.js
  src/components/LessonPage/MainLanguageButton.js
  src/components/LessonPage/PrintInfo.js
  src/components/LessonPage/ResetButton.js
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/LanguageDropdown.js
  src/components/PdfHeader.js
  src/components/PopoverComponent.js
  src/pages/LessonPage.js
  src/reducers/checkboxes.js
  src/reducers/language.js
  src/reducers/lastLesson.js
  src/reducers/mode.js
  src/reducers/showPlaylists.js
  src/resources/courseContent.js
  src/resources/courseFrontmatter.js
  src/resources/courses.js
  src/resources/lessonContent.js
  src/resources/lessonFrontmatter.js
  src/resources/lessons.js
  src/resources/playlists.js
  src/selectors/course.js
  src/selectors/lesson.js
  src/store.js
  src/util.js
  src/utils/checkboxUtils.js
  src/utils/filterUtils.js
  src/utils/localStorage.js
  src/utils/processContent.js
  src/utils/stringUtils.js
  src/utils/util.js
  test/utils/filterUtils_spec.js
  test/utils/stringUtils_spec.js
  test/utils/util_spec.js
Labels: PR: Needs Review

#542 Near perfect scores for accessibilty on frontpage
  src/components/CourseList/CourseItem.js
  src/components/CourseList/CourseList.js
  src/components/CourseList/CourseList.scss
  src/components/CourseList/ExternalCourseList.js
  src/components/CourseList/ExternalCourseList.scss
  src/components/CoursePage/LessonList.js
  src/components/CoursePage/LessonList.scss
  src/components/CoursePage/PlaylistNavigation.js
  src/components/CoursePage/PlaylistNavigation.scss
  src/components/Flag.js
  src/components/FrontPage/Courses.js
  src/components/FrontPage/Courses.scss
  src/components/FrontPage/StartButton.js
  src/components/FrontPage/StartButton.scss
  src/components/FrontPage/TeacherInfobox.js
  src/components/FrontPage/TeacherInfobox.scss
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/BreadCrumb.scss
  src/components/Navigation/ContinueButton.js
  src/components/Navigation/ContinueButton.scss
  src/components/Navigation/Footer.js
  src/components/Navigation/ModeDropdown.js
  src/components/Navigation/NavBar.js
  src/components/PdfHeader.scss
  src/components/PopoverComponent.js
  src/constants/captions_en.js
  src/constants/captions_nb.js
  src/constants/captions_nn.js
  src/pages/CoursePage.js
  src/pages/FrontPage.js
  src/pages/LessonPage.js
  src/pages/PageNotFound.js
Labels: PR: Reviewed w/ Comments

#521 Font for dyslexia
  package.json
  src/assets/fonts/OpenDyslexic-Regular.ttf
  src/components/FrontPage/TeacherInfobox.scss
  src/components/LessonPage/ImprovePage.scss
  src/components/Navigation/DyslexiaSwitch.js
  src/components/Navigation/DyslexiaSwitch.scss
  src/components/Navigation/Footer.js
  src/components/Navigation/Footer.scss
  src/components/Navigation/NavBar.scss
  src/components/PopoverComponent.js
  src/components/PopoverComponent.scss
  src/constants/captions_en.js
  src/constants/captions_nb.js
  src/constants/captions_nn.js
  src/pages/App.js
  src/pages/App.scss
  src/reducer.js
  src/reducers/showDyslexicFont.js
  src/store.js
  src/styles/_buttons.scss
  src/styles/_fonts.scss
  src/styles/variables.scss
  test/reducers/dyslexia_spec.js
  yarn.lock
Labels: PR: Needs Review

#550 Issue 528 fixed 404 error
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/ContinueButton.js
Labels: PR: Needs Review

#553 Add rel noopener to links to others sites
  src/components/CourseList/CourseItem.js
  src/components/CoursePage/LessonItem.js
  src/components/FrontPage/TeacherInfobox.js
  src/components/LessonPage/ImprovePage.js
  src/components/Navigation/Footer.js
  src/pages/LessonPage.js
Labels: PR: Needs Review

#555 Issue 481 fix internal links for yarn start
  webpack.config.babel.js
Labels: PR: Needs Review

#556 Minor accessibility fix
  src/components/FrontPage/TeacherInfobox.js
  src/components/FrontPage/TeacherInfobox.scss
  src/components/Navigation/Footer.js
  src/components/PopoverComponent.js
Labels: PR: Needs Review

#557 Tab through checkboxes
  src/components/LessonPage/Content.scss
Labels: PR: Reviewed w/ Comments

#561 Only render scratchblocks after hydration.
  src/components/LessonPage/Content.js
  src/reducer.js
  src/reducers/hydration.js
  src/renderDynamic.js
  src/utils/processContent.js
  test/reducers/hydration_spec.js
  webpack.config.babel.js
Labels: PR: Needs Review

#563 Fix warning prefix
  src/renderDynamic.js
  src/renderStatic.js
Labels: PR: Needs Review

#564 Sort courses taking all filterlanguages into account
  src/components/CourseList/LessonCount.js
  src/selectors/course.js
  src/selectors/lesson.js
  test/selectors/course_spec.js
  test/selectors/lesson_spec.js
Labels: PR: Needs Review

#567 Remove 2px of shadow below navbar
  src/components/Navigation/NavBar.scss
Labels: PR: Needs Review

#566 529 url ends with slash breaks
  server.js
  src/routes.js
Labels: PR: Needs Review

#569 Check that lesson.yml exists
  src/resources/lessonFrontmatter.js
  src/resources/lessons.js
Labels: PR: Needs Review

#574 Add building with PDFs in travis
  .travis.yml
  createLessonPdfs.js
  package.json
  travis_build.sh
  yarn.lock
Labels: PR: Needs Review

#578 Extra files, no copy of yml, only deploy for push to kodeklubben
  .travis.yml
  src/assets/deploy/.nojekyll
  src/assets/deploy/README.md
  src/assets/deploy/google91a144a83c954edb.html
  webpack.config.babel.js
Labels: PR: Needs Review

#579 Automatic deploy to kodeklubben/kodeklubben.github.io
  .travis.yml
Labels: PR: Needs Review

#575 Changed to pure components
  src/WithStylesContext.js
  src/components/CollapsiblePanel.js
  src/components/FrontPage/TeacherInfobox.js
  src/components/LessonPage/ToggleButton.js
  src/pages/LessonPage.js
Labels: PR: Needs Review

#573 Issue 551 functions for frontmatter
  src/components/CoursePage/LessonItem.js
  src/components/InstructionButton.js
  src/components/LessonPage/ButtonRow.js
  src/components/LessonPage/ImprovePage.js
  src/components/LessonPage/MainLanguageButton.js
  src/components/LessonPage/PdfButton.js
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/ContinueButton.js
  src/pages/LessonPage.js
  src/resources/lessonContent.js
  src/resources/lessonFrontmatter.js
  src/store.js
Labels: PR: Good to Merge

#582 Tabbing to accordion and popovercomponents
  package.json
  src/components/CollapsiblePanel.js
  src/components/CollapsiblePanel.scss
  src/components/CourseList/CourseItem.js
  src/components/CourseList/CourseItem.scss
  src/components/CoursePage/CourseInfo.js
  src/components/CoursePage/LessonItem.js
  src/components/CoursePage/LessonItem.scss
  src/components/CoursePage/LevelNavigation.js
  src/components/CoursePage/PlaylistNavigation.js
  src/components/CoursePage/PlaylistNavigation.scss
  src/components/Filter/FilterItem.js
  src/components/Filter/FilterItem.scss
  src/components/Filter/LessonFilter.js
  src/components/Filter/LessonFilter.scss
  src/components/Filter/RadioButtons.js
  src/components/InstructionButton.js
  src/constants/captions_en.js
  src/constants/captions_nb.js
  src/constants/captions_nn.js
  src/styles/customBootstrapStyles.js
  src/styles/mixins.scss
  yarn.lock
Labels: PR: Needs Review

#588 Outline for checkbox and one anchor for github in footer
  src/components/LessonPage/Content.scss
  src/components/Navigation/Footer.js
Labels: PR: Reviewed w/ Comments
