Repository kodeklubben/codeclub-viewer, pull requests merged in 2018-07, with the labels that each got.

#516 Remove markdown-it-anchor
  package.json
  webpack.config.babel.js
  yarn.lock
Labels: PR: Needs Review

#502 Issue 498 stopPropagation to onClick
  src/components/PopoverComponent.js
Labels: PR: Needs Review

#450 Add publish script
  README.md
  getBetaFork.js
  publish_beta.sh
Labels: PR: Reviewed w/ Comments

#524 Fix pdf and tooltips
  package.json
  src/components/LessonPage/PdfButton.js
  src/resources/courseFrontmatter.js
  src/resources/lessonFrontmatter.js
  src/util.js
  webpack.config.babel.js
Labels: PR: Needs Review, bug

#495 Issue 480 add license
  src/components/LessonPage/ImprovePage.scss
  src/constants/captions_da.js
  src/constants/captions_en.js
  src/constants/captions_nb.js
  src/constants/captions_nn.js
  src/constants/captions_sv.js
  src/pages/LessonPage.js
  src/pages/LessonPage.scss
  src/resources/lessons.js
Labels: PR: Reviewed w/ Comments

#503 Issue 318 add tooltips for filtertags
  src/components/Filter/FilterGroup.js
  src/components/Filter/FilterItem.js
  src/components/Filter/FilterItem.scss
  src/selectors/translate.js
Labels: PR: Needs Review

#526 Collapse filter translators
  src/components/Filter/FilterGroup.js
  src/components/Flag.js
  src/components/LessonPage/MainLanguageButton.js
  src/components/Navigation/LanguageDropdown.js
  src/pages/LessonPage.js
  src/selectors/translate.js
Labels: PR: Needs Review

#533 Make createLessonPdfs.js more robust
  createLessonPdfs.js
  package.json
  pathlists.js
  server.js
  yarn.lock
Labels: PR: Needs Review

#536 Issue 527 MainLanguageButton for external lessons fix
  src/components/LessonPage/MainLanguageButton.js
Labels: PR: Needs Review

#538 Only get level from lesson.yml files.
  src/components/CoursePage/LessonItem.js
  src/components/Navigation/BreadCrumb.js
  src/pages/LessonPage.js
  src/resources/lessonFrontmatter.js
  src/resources/lessons.js
Labels: PR: Needs Review

#537 Use my fork of scratchblocks
  package.json
  yarn.lock
Labels: PR: Good to Merge
