Repository kodeklubben/codeclub-viewer, pull requests merged in 2019-10, with the labels that each got.

#638 Håper dette er nok tid til å rendre microbit snake.
  createLessonPdfs.js
Labels: PR: Needs Review

#625 Function components
  .eslintrc
  package.json
  src/WithStylesContext.js
  src/components/CollapsiblePanel.js
  src/components/CourseList/CourseItem.js
  src/components/CourseList/LessonCount.js
  src/components/CoursePage/LessonItem.js
  src/components/CoursePage/LessonList.js
  src/components/CoursePage/LevelNavigation.js
  src/components/CoursePage/PlaylistNavigation.js
  src/components/Filter/ClearFilterButton.js
  src/components/Filter/FilterGroup.js
  src/components/Filter/FilterItem.js
  src/components/Filter/LessonFilter.js
  src/components/Filter/RadioButtons.js
  src/components/Flag.js
  src/components/FrontPage/Courses.js
  src/components/FrontPage/TeacherInfobox.js
  src/components/InstructionButton.js
  src/components/LessonPage/Content.js
  src/components/LessonPage/ImprovePage.js
  src/components/LessonPage/MainLanguageButton.js
  src/components/LessonPage/PdfButton.js
  src/components/LessonPage/PrintInfo.js
  src/components/LessonPage/Progress.js
  src/components/LessonPage/ResetButton.js
  src/components/LessonPage/ToggleButton.js
  src/components/LevelIcon.js
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/ContinueButton.js
  src/components/Navigation/DyslexiaSwitch.js
  src/components/Navigation/Footer.js
  src/components/Navigation/LanguageDropdown.js
  src/components/Navigation/ModeDropdown.js
  src/components/Navigation/NavBar.js
  src/components/Navigation/NavLink.js
  src/components/PdfHeader.js
  src/components/PopoverComponent.js
  src/pages/App.js
  src/pages/CoursePage.js
  src/pages/LessonPage.js
  src/pages/PageNotFound.js
  src/renderDynamic.js
  src/renderStatic.js
  src/utils/processContent.js
  src/utils/renderMicrobit.js
  src/utils/renderScratchblocks.js
  src/utils/renderToggleButtons.js
  yarn.lock
Labels: PR: Reviewed w/ Comments

#651 Add font-display to dyslexic font for better performance
  src/styles/_fonts.scss
Labels: PR: Good to Merge
