Repository kodeklubben/codeclub-viewer, pull requests merged in 2019-11, with the labels that each got.

#641 React-redux 7.1 with useSelector and useDispatch
  .eslintrc
  package.json
  src/components/CollapsiblePanel.js
  src/components/CourseList/CourseItem.js
  src/components/CourseList/CourseList.js
  src/components/CourseList/ExternalCourseList.js
  src/components/CourseList/LessonCount.js
  src/components/CoursePage/CourseInfo.js
  src/components/CoursePage/LessonItem.js
  src/components/CoursePage/LessonList.js
  src/components/CoursePage/LessonWrapper.js
  src/components/CoursePage/LevelNavigation.js
  src/components/CoursePage/PlaylistNavigation.js
  src/components/Filter/ClearFilterButton.js
  src/components/Filter/FilterGroup.js
  src/components/Filter/FilterItem.js
  src/components/Filter/LessonFilter.js
  src/components/Filter/RadioButtons.js
  src/components/Flag.js
  src/components/FrontPage/Courses.js
  src/components/FrontPage/TeacherInfobox.js
  src/components/Head.js
  src/components/InstructionButton.js
  src/components/LessonPage/ButtonRow.js
  src/components/LessonPage/Content.js
  src/components/LessonPage/ImprovePage.js
  src/components/LessonPage/MainLanguageButton.js
  src/components/LessonPage/PdfButton.js
  src/components/LessonPage/PrintInfo.js
  src/components/LessonPage/Progress.js
  src/components/LessonPage/ResetButton.js
  src/components/LessonPage/ToggleButton.js
  src/components/LevelIcon.js
  src/components/MarkdownRenderer.js
  src/components/Navigation/BreadCrumb.js
  src/components/Navigation/ContinueButton.js
  src/components/Navigation/DyslexiaSwitch.js
  src/components/Navigation/Footer.js
  src/components/Navigation/LanguageDropdown.js
  src/components/Navigation/ModeDropdown.js
  src/components/Navigation/NavBar.js
  src/components/PdfHeader.js
  src/components/PopoverComponent.js
  src/pages/App.js
  src/pages/CoursePage.js
  src/pages/FrontPage.js
  src/pages/LessonPage.js
  src/pages/PageNotFound.js
  src/reducers/checkboxes.js
  src/resources/lessonFrontmatter.js
  src/store.js
  src/styles/_nav.scss
  src/utils/checkboxUtils.js
  yarn.lock
Labels: PR: Needs Review

#656 Small fixes after merging PR 641.
  src/components/Navigation/NavBar.js
  src/utils/checkboxUtils.js
Labels: PR: Good to Merge

#653 Issue 623: Sort CourseItems consistently
  src/selectors/course.js
Labels: PR: Needs Review

#657 654: Fix filter checkboxes
  src/components/LessonPage/Content.js
  src/components/LessonPage/Content.scss
Labels: PR: Needs Review, bug

#658 Issue 655 Object.prototype rule
  .eslintrc
  src/reducers/filter.js
  src/selectors/filter.js
  src/selectors/translate.js
  src/utils/processContent.js
  test-links.js
Labels: PR: Good to Merge
